### ISSUE TITLE
Remove old dependency EChatroomNotificationLevel

### ISSUE THREAD

**Issue by d3v0e** [DoctorMcKay/node-steam-user#316] opened 2020-06-06 23:24 UTC
In the file /resources/enums.js, EChatRoomNotificationLevel is requested to request the old dependence

SteamUser.EChatRoomMemberStateChange = require('../enums/EChatRoomMemberStateChange.js');
**SteamUser.EChatRoomNotificationLevel = require('../enums/EChatRoomNotificationLevel.js');**
SteamUser.EChatRoomServerMessage = require('../enums/EChatRoomServerMessage.js');
SteamUser.EChatRoomServerMsg = require('../enums/EChatRoomServerMsg.js');
SteamUser.EChatRoomType = require('../enums/EChatRoomType.js');
**SteamUser.EChatroomNotificationLevel = require('../enums/EChatroomNotificationLevel.js');**
SteamUser.EClanPermission = require('../enums/EClanPermission.js');
SteamUser.EClanRank = require('../enums/EClanRank.js');
SteamUser.EClanRelationship = require('../enums/EClanRelationship.js');

**Comment by DoctorMcKay** [comment] 2020-06-07 00:35
Duplicate of #315.

**Closed by DoctorMcKay** 2020-06-07 00:35 UTC
Labels: bug, duplicate
