### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 2cab** [DoctorMcKay/node-steam-user#289] opened 2020-03-04 22:31 UTC
`C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\connection.js:21
        this._connection.stream.setTimeout(0);
                                ^

TypeError: Cannot read property 'setTimeout' of undefined
    at SteamUser.<anonymous> (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\connection.js:21:26)
    at C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:480:7)
    at TCPConnection._readMessage (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
    at Socket.emit (events.js:311:20)
    at emitReadable_ (_stream_readable.js:562:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)`

**Comment by DoctorMcKay** [comment] 2020-03-05 03:33
Duplicate of #274.

**Closed by DoctorMcKay** 2020-03-05 03:33 UTC
Labels: bug
