### ISSUE TITLE
Events to Promises

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#299] opened 2020-04-24 11:14 UTC
When I tried to use `steam-user` with `Promises` I was surprised how it was implemented. Yes, you could use promises for certain functions, but you still have events with callbacks.
I was expecting I could use `let details = await client.logOn(credentials)`, but unfortunately I still have to use events with callbacks to accomplish this.
I'm wondering if you could support these constructions, so no callbacks are needed at all. I'm imagining you could use `EventListener.once("event", resolve)` to make some of these work.

**Comment by DoctorMcKay** [comment] 2020-04-24 16:21
Duplicate of #286.

Promises are a replacement for callbacks, not for events.

**Closed by DoctorMcKay** 2020-04-24 16:21 UTC
Labels: enhancement

**Comment by Revadike** [comment] 2020-04-24 17:35
I know they are different, but I'm suggesting to promisify once-events.

**Comment by DoctorMcKay** [comment] 2020-04-25 02:50
I already went into detail in #286 why promisifying `logOn` is not possible. What other events do you think should be promises instead?

**Comment by Revadike** [comment] 2020-04-25 02:52
all events actually

**Comment by DoctorMcKay** [comment] 2020-04-25 02:56
How would `disconnected` be promisified?

**Comment by Revadike** [comment] 2020-04-25 03:07
> How would `disconnected` be promisified?

`new Promise((res, rej) => client.once("disconnected", (err) => err ? rej(err) : res()))`

**Comment by ezraripps** [comment] 2020-04-25 03:53
@Revadike why dont you fork the repo, make a PR. $100 to promisify all the same features without losing any functionality

**Comment by DoctorMcKay** [comment] 2020-04-25 04:16
@Revadike So where is that Promise returned to the implementing application?

**Comment by Revadike** [comment] 2020-04-25 13:29
> @Revadike So where is that Promise returned to the implementing application?

idk, could be `await client.once("disconnected")` or simply `await client.disconnected()`.

**Comment by ezraripps** [comment] 2020-05-05 00:08
> > @Revadike So where is that Promise returned to the implementing application?
> 
> 
> 
> idk, could be `await client.once("disconnected")` or simply `await client.disconnected()`.

what if the client disconnects twice?

**Comment by Revadike** [comment] 2020-05-05 00:34
> > > @Revadike So where is that Promise returned to the implementing application?
> > 
> > 
> > idk, could be `await client.once("disconnected")` or simply `await client.disconnected()`.
> 
> what if the client disconnects twice?

It only looks checks for the first disconnect.

**Comment by DoctorMcKay** [comment] 2020-05-05 01:19
> It only looks checks for the first disconnect.

Yes, that's exactly the reason why `disconnected` is an event and not a promise.

**Comment by Revadike** [comment] 2020-05-05 02:45
Yup, it sure it an event. I don't know what you guys are getting at. It functions as a `once`. If you want to listen to the event forever, I guess u can loop it.

```js
while (something) {
await client.disconnected();
//do stuff while disconnected
}```

but in practice, you really want to just do this:

```js
await client.signOff();
process.exit()
```

**Comment by DoctorMcKay** [comment] 2020-05-05 04:12
Having logOff() return a promise is a completely different request from shoehorning all events into promises.
