### ISSUE TITLE
InvalidPassword error when try login with loginKey

### ISSUE THREAD

**Issue by hanahaneull** [DoctorMcKay/node-steam-user#333] opened 2020-11-08 17:46 UTC
## Describe the bug
Got ``InvalidPassword`` error when try login with loginKey

Code:
```js
steam.logOn({
			accountName: config.steam.username,
			loginKey: key,
		});
```

## Versions
steam-user: v4.18.0
nodejs: v15.0.1
steam-totp: v2.1.1

## Screenshots and Error Logs
```js
[STEAM ERROR] Error: InvalidPassword
    at SteamUser.<anonymous> (/home/x/Archive/Projects/xx/node_modules/steam-user/components/logon.js:494:16)
    at /home/x/Archive/Projects/xx/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/home/x/Archive/Projects/xx/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/home/x/Archive/Projects/xx/node_modules/steam-user/components/messages.js:571:24)
    at SteamUser._handleNetMessage (/home/x/Archive/Projects/xx/node_modules/steam-user/components/messages.js:506:7)
    at SteamUser.processMulti (/home/x/Archive/Projects/xx/node_modules/steam-user/components/messages.js:598:9)
    at SteamUser.<anonymous> (/home/x/Archive/Projects/xx/node_modules/steam-user/components/messages.js:592:16)
    at /home/x/Archive/Projects/xx/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>) {
  eresult: 5
}
```

**Comment by DoctorMcKay** [comment] 2020-11-09 04:21
Your login key is incorrect. How are you obtaining it?

**Comment by hanahaneull** [comment] 2020-11-09 08:51
I listen on ``loginKey`` events to get the login key and save it to ``key.json``

```javascript
steam.on('loginKey', (key) => {
	console.log(`Got loginKey from steam: ${key}`);
	fs.readFile('./key.json', (err, data) => {
		if (err) throw err;
		let keydata = JSON.parse(data);
		keydata.key = key;
		const keysave = JSON.stringify(keydata, null, 2);
		fs.writeFile('./key.json', keysave, (err) => {
			if (err) throw err;
			console.log(`Key saved to key.json`);
		});
  	});
});
```
So now ``key.json`` would look like this  


```js
{
  "key": "LVP3fxxxxxGEDMxxx6I"
}
```

So after that if the ``key`` value exist in ``key.json``, the login would be using ``loginKey`` instead ``password``

```js
const login = () => {
	const { key } = require('./key.json');
	if (key) {
		steam.logOn({
			accountName: config.steam.username,
			loginKey: key,
		});
	} else
		steam.logOn({
			accountName: config.steam.username,
			password: config.steam.password,
			rememberPassword: true,
		});
};

login();
```

**Comment by DoctorMcKay** [comment] 2020-11-10 00:30
Do you always get this result when using a login key, or just sometimes?

**Comment by hanahaneull** [comment] 2020-11-10 10:32
Yes, never success login with ``loginKey``

**Comment by strd0x** [comment] 2020-11-14 10:19
I faced the same problem, but I get it sometimes, not always

**Comment by FuTTiiZ** [comment] 2021-01-11 13:50
Any fix for this?

**Comment by deepbluev7** [comment] 2021-02-17 22:09
I can somewhat reliably reproduce this using the mx-puppet-steam matrix <-> steam bridge. Anything I could do to help debug this?

**Comment by fcastrocs** [comment] 2021-02-20 08:04
I've been testing, it seems you can only use the loginkey for accounts with mobile auth, and you must use sentry for accounts with email auth.

**Comment by DoctorMcKay** [comment] 2021-03-29 03:09
Logging on with loginKeys has never really worked reliably, and I've never quite been able to figure out why...

**Comment by fcastrocs** [comment] 2021-04-02 17:40
> Logging on with loginKeys has never really worked reliably, and I've never quite been able to figure out why...

I don't know if you are aware, but Steam sends you a new login key at random times. I have used loginkey signin in a 2FA account without problems for a while. No need for the secret key to generate codes.

**Comment by deepbluev7** [comment] 2021-04-03 10:45
@fcastrocs Is that with email based SteamGuard?

**Comment by fcastrocs** [comment] 2021-04-03 17:13
> @fcastrocs Is that with email based SteamGuard?

Just use sentry for this.

**Comment by deepbluev7** [comment] 2021-04-03 20:33
I'm pretty sure I am using sentry, and it doesn't work, but maybe you can tell me what we are doing wrong here? https://github.com/icewind1991/mx-puppet-steam/blob/master/src/steam.ts

**Comment by SamHoque** [comment] 2021-06-15 20:27
Anyone found a viable solution for this yet?

**Comment by JokerGermany** [comment] 2021-07-27 23:03
Same Problem.
After entering the steam guard code and i get a new email from Steam with exact the same SteamGuard Code.
After a restart he sends a new steamguard code.

**Comment by FuTTiiZ** [comment] 2021-07-28 12:39
> After entering the steam guard code and i get a new email from Steam with exact the same SteamGuard Code.
> After a restart he sends a new steamguard code.
If you request SteamGuard codes in quick succession, you'll get the same code, as they change with time and not after each use

**Comment by Ankumo** [comment] 2021-12-04 10:38
Noticed something strange. When I'm logging in with password and obtaining new loginKey and then trying to relog, it throws Invalid Password. But as soon as server restarted this invalid key works again even after 15 relogs. Hope that'd help

**Comment by DoctorMcKay** [comment] 2022-01-22 20:52
It looks like bitlbee-steam is using WebAPI mobile logons, which wouldn't get you a CM session.

**Comment by bertiebaggio** [comment] 2022-01-23 12:02
Thank you for your response :)

I'm completely oblivious to the differences; but I take it CM* is preferred and/or provides a fuller API. bitlbee-steam doesn't offer group chats, for example; though whether this is due to limitations in API or dev time I don't know.

(*CM is 'Connection Manager', right? it's a surprisingly tricky acronym to track down if you don't know it in advance!)

It seems odd that SteamGuard-email works just fine for WebAPI logins and indeed regular Steam client logins; but not for CM sessions.

My node/TS knowledge is limited but I am motivated to help, is there any way I can assist with this? Or is it a case of the problem is unsolvable until Steam resolves whatever the issue is with SG/auth flow on their side?

**Comment by DoctorMcKay** [comment] 2022-01-23 15:40
WebAPI sessions are the same thing the mobile app uses, so it's going to be as limited as the app is. CMs are what the proper Steam client connects to, so you can do anything the desktop client can do through a CM.

All I can figure is that there's something I'm missing regarding how the proper Steam client logs on using login keys. Maybe I'll be able to dump some traffic and look for a pattern.

**Comment by UmbraChimera** [comment] 2022-04-26 05:02
Has there been any updates on this? I'm using mobile 2fa and still can't get this to work with the puppet downstream.

**Comment by fthdgn** [comment] 2023-01-01 12:10
I have the same problem. Does this library work different than https://github.com/SteamRE/SteamKit.
I did't have any problem with the C# library. It may help to solve the problem.

**Comment by plantroon** [comment] 2023-03-08 19:07
Same problem from mx-puppet-bridge which uses this tool. My steam account has OTP winauth/mobile app equivalent, so not email auth.

**Comment by DoctorMcKay** [comment] 2023-03-18 04:49
Closing this as login keys are now deprecated in [4.28.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.28.0).

**Closed by DoctorMcKay** 2023-03-18 04:49 UTC
Labels: bug
