### ISSUE TITLE
Timeout chat message

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#404] opened 2022-09-18 15:30 UTC
## Describe the bug
This has been a long time issue for me with my chat bot. This seems to happen more often when the chat bot has a lot of messages to send, but your `sendFriendMessage` function reports a timeout error, even though the message had actually been sent successfully. This causes my bot to send duplicate messages, and it is pretty messy. Maybe increasing the timeout is all that's needed to fix this issue, but I haven't tried that yet.

## Versions
v16.15.1

## Screenshots and Error Logs
`Request timed out`

**Comment by DoctorMcKay** [comment] 2022-09-18 19:31
Do you have any repro case? I kinda suspect that Steam just occasionally fails to respond for chat messages.

**Comment by Revadike** [comment] 2022-09-18 19:53
Not really

**Comment by nolddor** [comment] 2022-10-26 09:30
Same problem here, eventually `sendFriendMessage` fails with a timeout error even if the message has been actually send.
Haven't found a use case to replicate this odd behaviour at my own, it seems a random error.

**Comment by Revadike** [comment] 2022-11-06 03:38
Some example log:

```
 2022-11-06 | 04:33:20.747 | ERROR | function                       | Failed to send steam message '⁢
Great! I did not detect anything wrong with our accepted trade offer!
Please send me the steam keys for Vertigo FPS, Wilma's Dreams and City Things to proceed.' to 76561198093753361: Request timed out
...
 2022-11-06 | 04:35:17.156 | INFO  | sentSteamChatMessage           | Revadike > ➳+D-G+➳: ⁢
Great! I did not detect anything wrong with our accepted trade offer!
Please send me the steam keys for Vertigo FPS, Wilma's Dreams and City Things to proceed.
```

In steam chat window:
![image](https://user-images.githubusercontent.com/4411977/200152901-708710ad-9060-43fe-80c7-4b6eaa234d5a.png)

**Comment by Revadike** [comment] 2023-02-09 14:59
@DoctorMcKay got time to look into this perhaps this weekend? 🤞

**Comment by nolddor** [comment] 2023-05-07 10:45
Prolly we need to increase the timeout at here?
Still suffering from this issue...

At my bot logs:
```
[2023-05-07 12:40:28] [Chat] Unable to send chat message to Вячеслав Кульбин (76561198198507028). Retrying in 10 seconds...
  > Reason: Request timed out, Code: -
```

But the message was delivered, notice the message twice at chats:
![imagen](https://user-images.githubusercontent.com/1280022/236672842-1a4bbb87-971a-4769-8874-85e70bae32bc.png)

**Comment by DoctorMcKay** [comment] 2023-05-08 17:43
The timeout is 10 seconds. I really doubt the timeout needs to be lengthened; rather I think this is Steam being Steam and just failing to respond entirely to some chat messages. I haven't had a chance to confirm my suspicions though.

**Comment by nolddor** [comment] 2023-05-08 17:46
> The timeout is 10 seconds. I really doubt the timeout needs to be lengthened; rather I think this is Steam being Steam and just failing to respond entirely to some chat messages. I haven't had a chance to confirm my suspicions though.

is there anything i can add to my code to help you to confirm if Steam is just being Steam? I see the bug every now and them.. maybe I can catch something that help us to understand what's the root cause.

**Comment by Revadike** [comment] 2023-05-08 18:07
Well, thanks for issue bump. Hopefully this issue won't see 1y of age, but we'll see.

**Comment by DoctorMcKay** [comment] 2023-05-08 18:45
I just don't really think there's anything to be done here except potentially just ignoring timeouts entirely. But that would mean that I'd have to resolve the promise rather than rejecting it when the timeout period elapses to prevent things from hanging.

**Comment by nolddor** [comment] 2023-05-08 18:55
I meant to determine if Steam just is slow (> 10 secs) or basically he is not replying anything at all even if we wait for 5min before to timeout. But yeah,.. there is not good solution because if you resolve the promise after the given timeout that will mask legit timeouts as well... Well,.. If i have to choose I think is better to think the message was not delivered and sent it twice than assume it was delivered and it does not deliver any when a legit timeout occurs...

Steam making simple things more hard than anyone can imagine...

**Comment by DoctorMcKay** [comment] 2023-05-08 19:02
I think it probably won't be that big of a deal to just assume every timeout actually succeeded. The old chat system doesn't have any way of determining if a message succeeded; it's just fire-and-forget. I don't remember hearing of any issues with messages not being delivered successfully.

Basically, unless we get an explicit error right away, I think it's probably safe to assume it succeeded.

**Comment by Revadike** [comment] 2023-05-08 19:17
Perhaps other steam chat libraries reveal some info.

**Comment by nolddor** [comment] 2023-05-13 07:21
For the time being,... I'm following @DoctorMcKay suggestion and I started to disregard any timeout error to assume it was delivered sucessfully. I haven't detected any case where the timed out message was actually not delivered as per @DoctorMcKay assumptions above. I think it is safe to just omit this kind of error at our code.

From:
```
[2023-05-07 12:40:28] [Chat] Unable to send chat message to Вячеслав Кульбин (76561198198507028). Retrying in 10 seconds...
  > Reason: Request timed out, Code: -
```
To:
```
[2023-05-13 00:20:30] [Chat] Send chat message to MadHunter (76561198976671816) timed out. Most likely our message was delivered...                                                      
  > Reason: Request timed out, Code: -  
``` 

Cheers!

**Comment by Revadike** [comment] 2023-05-13 10:30
I have a suggestion, this is more like workaround. You could make it an option to enable. How it works is, if you receive a timeout, you then first query https://help.steampowered.com/en/accountdata/GetFriendMessagesLog (or its Load More API) to check if the message was actually sent or not.

**Comment by DoctorMcKay** [comment] 2023-06-27 05:03
Closing this since it doesn't appear that there's really anything we can do about it.

**Closed by DoctorMcKay** 2023-06-27 05:03 UTC
Labels: bug
