### ISSUE TITLE
'tradeOffers' event not fired reliably

### ISSUE THREAD

**Issue by florianmrz** [DoctorMcKay/node-steam-user#162] opened 2018-03-07 16:30 UTC
Commit 2672916d7ea0a037068e6a45d1b729f96450a0ec is causing the `tradeOffers` event to not fire if the user received a new trade offer after handling an old one, since the **amount** of incoming trade offers didn't change.

- Is this intended behaviour?
- Should I update the `_lastTradeOfferCount` property manually after handling an incoming trade offer?
- What was the reason behind implementing the check in the first place?

Thanks!

**Comment by DoctorMcKay** [comment] 2018-03-07 19:20
How frequently are you receiving a new trade offer at the same exact time as you act on one?

No, you shouldn't ever touch underscored properties.

The reason this was implemented is because sometimes Steam can continually send trade offer notification messages with the same count when nothing changed.

**Comment by florianmrz** [comment] 2018-03-07 19:40
Here's an example scenario where this was causing issues:

- Bot receives trade offer:
`tradeOffers` event fires with `amount` set to 1, `_lastTradeOfferCount` is now 1.
- Bot acts on trade offer (accepts / declines).
- Trade offer is no longer active, amount of incoming trade offers is now `0`.
- Bot receives another trade offer:
`_lastTradeOfferCount` is still at `1`, thus nothing changed and event is not fired.

Hope this explains exactly what I meant.

**Comment by DoctorMcKay** [comment] 2018-03-07 19:53
That scenario would not cause an issue.

1. Bot receives trade offer
    - `tradeOffers` event fires with `amount` set to 1
    - `_lastTradeOfferCount` is now 1
2. Bot acts on trade offer
3. Trade offer is no longer active
    - `tradeOffers` event fires with `amount` set to 0 since 0 != 1
    - `_lastTradeOfferCount` is now 0
4. Bot receives another trade offer
    - `tradeOffers` event fires with `amount` set to 1 since 1 != 0
    - `_lastTradeOfferCount` is now 1

**Comment by florianmrz** [comment] 2018-03-07 20:03
That makes sense, but the issue here is that I have never received the `tradeOffers` event with an amount of `0`, it was only ever reporting positive values.
Quick way to reproduce this was by sending a trade offer to the bot (`tradeOffers` fired with `1`), then cancelling the trade offer from my end (`tradeOffers` did not fire at all).

**Comment by DoctorMcKay** [comment] 2018-03-07 20:09
Yep, I see a bug. The problem is that notification messages with a count of 0 aren't being handled properly.

**Comment by florianmrz** [comment] 2018-03-07 20:12
Alright, thanks a lot for looking into it!

**Comment by DoctorMcKay** [comment] 2018-03-07 20:13
This is fixed in v3.25.2.

**Closed by DoctorMcKay** 2018-03-07 20:13 UTC
Labels: bug
