### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tabam1** [DoctorMcKay/node-steam-user#223] opened 2019-02-12 19:04 UTC
/steam-user/components/chatroom.js:571
	str = str.replace(/\\\[/g, replacement);
	          ^

TypeError: Cannot read property 'replace' of null
    at parseBbCode (/steam-user/components/chatroom.js:571:12)

**Comment by DoctorMcKay** [comment] 2019-02-12 22:53
Duplicate of #222.

**Closed by DoctorMcKay** 2019-02-12 22:53 UTC
Labels: bug, duplicate
